[versions]
zxing = "3.5.3"
anr_watchdog = "1.4.0"
ax_runner = "1.7.0"
leakcanary = "2.14"
koinAndroid = "4.1.1"
koinAndroidxCompose = "4.1.1"

okhttp = "5.1.0"

[plugins]

[libraries]
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }

anrWatchdog = { module = "com.github.anrwatchdog:anrwatchdog", version.ref = "anr_watchdog" }
zxing-core = { module = "com.google.zxing:core", version.ref = "zxing" }

androidx-core-ktx = { module = "androidx.core:core-ktx", version = "1.17.0" }
androidx-appcompat-core = { module = "androidx.appcompat:appcompat", version = "1.7.1" }
androidx-leanback-core = { module = "androidx.leanback:leanback", version = "1.2.0" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version = "1.12.2" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version = "1.10.1" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version = "2.9.3" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "ax_runner" }
androidx-splashscreen = { module = "androidx.core:core-splashscreen", version = "1.0.1" }

koin-android = { module = "io.insert-koin:koin-android", version.ref = "koinAndroid" }
koin-android-compat = { module = "io.insert-koin:koin-android-compat", version.ref = "koinAndroid" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koinAndroidxCompose" }

leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanary" }

[bundles]
