[versions]
kotlin = { strictly = "2.3.0" }
coroutines = "1.10.2"
serialization = "1.10.0-RC"
ktorio = "3.3.3"
ksp = "2.3.4"
kover = "0.9.4"
datetime = "0.7.1"
spotless = "8.1.0"
koin = "4.1.1"
agp = "9.0.0"
kotest = "6.1.3"
redacted = "1.15.1"
poko = "0.21.1"

[plugins]
multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
jsPlainObjects = { id = "org.jetbrains.kotlin.plugin.js-plain-objects", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
downloadPlugin = "de.undercouch.download:5.6.0"
kotest = { id = "io.kotest.multiplatform", version.ref = "kotest" }
redacted = { id = "dev.zacsweers.redacted", version.ref = "redacted" }
poko = { id = "dev.drewhamilton.poko", version.ref = "poko" }

[libraries]
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-jdk8 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
serialization-plugin = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "serialization" }
serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "datetime" }
poko = { module = "dev.drewhamilton.poko:poko-gradle-plugin", version.ref = "poko" }
redacted = { module = "dev.zacsweers.redacted:redacted-compiler-plugin-gradle", version.ref = "redacted" }
redacted-annotations = { module = "dev.zacsweers.redacted:redacted-compiler-plugin-annotations", version.ref = "redacted" }
agp = { module = "com.android.tools.build:gradle", version.ref = "agp" }
spotless-plugin = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }
kotlin-gradle-conventions = "org.gradle.kotlin:gradle-kotlin-dsl-conventions:0.9.0"
ktor-serialization = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktorio" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktorio" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktorio" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktorio" }
ktor-client-js = { module = "io.ktor:ktor-client-js", version.ref = "ktorio" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktorio" }
ktor-client-apache = { module = "io.ktor:ktor-client-apache", version.ref = "ktorio" }
ktor-client-contentNegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktorio" }
ktor-client-websockets = { module = "io.ktor:ktor-client-websockets", version.ref = "ktorio" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktorio" }
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktorio" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktorio" }
ktor-server-sessions = { module = "io.ktor:ktor-server-sessions", version.ref = "ktorio" }
ktor-server-tests = { module = "io.ktor:ktor-server-test-host", version.ref = "ktorio" }
ktor-server-metrics = { module = "io.ktor:ktor-server-metrics", version.ref = "ktorio" }
ktor-server-partialContent = { module = "io.ktor:ktor-server-partial-content", version.ref = "ktorio" }
ktor-server-contentNegotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktorio" }
ktor-server-forwardedHeader = { module = "io.ktor:ktor-server-forwarded-header", version.ref = "ktorio" }
ktor-server-autoHeadResponse = { module = "io.ktor:ktor-server-auto-head-response", version.ref = "ktorio" }
ktor-server-defaultHeaders = { module = "io.ktor:ktor-server-default-headers", version.ref = "ktorio" }
ktor-server-cachingHeaders = { module = "io.ktor:ktor-server-caching-headers", version.ref = "ktorio" }
ktor-server-callLogging = { module = "io.ktor:ktor-server-call-logging", version.ref = "ktorio" }
ktor-server-statusPages = { module = "io.ktor:ktor-server-status-pages", version.ref = "ktorio" }
ktor-server-compression = { module = "io.ktor:ktor-server-compression", version.ref = "ktorio" }
ktor-server-cors = { module = "io.ktor:ktor-server-cors", version.ref = "ktorio" }
ktor-server-auth = { module = "io.ktor:ktor-server-auth", version.ref = "ktorio" }
ktor-server-authJwt = { module = "io.ktor:ktor-server-auth-jwt", version.ref = "ktorio" }
ktor-server-websockets = { module = "io.ktor:ktor-server-websockets", version.ref = "ktorio" }
ksp = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotest-framework-engine = { module = "io.kotest:kotest-framework-engine", version.ref = "kotest" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-property = { module = "io.kotest:kotest-property", version.ref = "kotest" }
